# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-15 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdriver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
